# Generated by Django 4.2.4 on 2023-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvs',
            name='CV',
            field=models.FileField(null=True, upload_to='CV_files'),
        ),
    ]
